import type { Metadata } from "next";
import { Noto_Sans_KR, Lora } from "next/font/google";
import "./globals.css";
import {
  ThemeInitScript,
  ThemeProvider,
} from "@/components/theme/theme-provider";
import ReactQueryProvider from "@/components/provider/react-quer-provier";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

const notoSans = Noto_Sans_KR({
  variable: "--font-sans",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <ThemeInitScript />
        </head>
        <ThemeProvider>
          <body
            className={`${notoSans.variable} ${lora.variable} font-sans bg-background text-foreground antialiased transition-colors duration-200`}
            suppressHydrationWarning
          >
            <TooltipProvider>
              {children}
              <Toaster />
            </TooltipProvider>
          </body>
        </ThemeProvider>
      </html>
    </ReactQueryProvider>
  );
}
