import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import {
  ThemeInitScript,
  ThemeProvider,
} from "@/components/theme/theme-provider";
import TopNav from "@/components/nav/top-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeInitScript />
      </head>
      <ThemeProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} bg-background text-foreground antialiased transition-colors duration-200`}
          suppressHydrationWarning
        >
          <TopNav />
          <div className="pt-16">{children}</div>
        </body>
      </ThemeProvider>
    </html>
  );
}
